language: golang

go:
  - 1.4

before_install:
  - sudo apt-get install libmagickwand-dev


install:
  - go get github.com/vanng822/imgscale/imagick
  - go get github.com/vanng822/imgscale/imgscale
  - go get github.com/stretchr/testify/assert

script:
  - cd imagick && go test -v
  - cd .. 
  - cd imgscale && go test -v 
